"""
data.py  –  Tata Motors car database
All specs are approximate / representative figures.
Images: place .png files in the images/ folder beside app.py
"""

CATEGORIES = ["Hatchback", "Sedan", "SUV", "Compact SUV", "MUV", "Electric"]

TATA_CARS = [
    {
        "name": "Tata Tiago",
        "image": "tiago.png",
        "emoji": "🔵",
        "category": "Hatchback",
        "price_min": 6.0, "price_max": 9.5,
        "engine": "1.2L Revotron Petrol",
        "power": "86 PS", "torque": "113 Nm",
        "transmission": "5MT / AMT", "fuel": "Petrol",
        "mileage": "19.8 kmpl", "seating": 5, "boot": 242,
        "safety": "4-Star (GNCAP)",
        "tags": ["Budget", "City Car", "AMT Available"],
        "tagline": "Smart, safe, and incredibly affordable city companion.",
        "score_performance": 6, "score_comfort": 6, "score_safety": 7,
        "score_value": 9, "score_tech": 6, "score_space": 5,
    },
    {
        "name": "Tata Tiago EV",
        "image": "tiago_ev.png",
        "emoji": "⚡",
        "category": "Electric",
        "price_min": 8.5, "price_max": 12.0,
        "engine": "Electric Motor",
        "power": "74 PS", "torque": "114 Nm",
        "transmission": "Single Speed AT", "fuel": "Electric",
        "mileage": "315 km range", "seating": 5, "boot": 242,
        "safety": "4-Star (GNCAP)",
        "tags": ["EV", "Zero Emission", "Budget EV"],
        "tagline": "India's most affordable electric car – green and smart.",
        "score_performance": 6, "score_comfort": 6, "score_safety": 7,
        "score_value": 8, "score_tech": 7, "score_space": 5,
    },
    {
        "name": "Tata Altroz",
        "image": "altroz.png",
        "emoji": "🟣",
        "category": "Hatchback",
        "price_min": 6.9, "price_max": 11.0,
        "engine": "1.2L Revotron / 1.5L Diesel",
        "power": "86–100 PS", "torque": "113–200 Nm",
        "transmission": "5MT / DCT", "fuel": "Petrol / Diesel",
        "mileage": "19.4–25.1 kmpl", "seating": 5, "boot": 345,
        "safety": "5-Star (GNCAP)",
        "tags": ["5-Star Safety", "Premium Hatch", "DCT"],
        "tagline": "India's first 5-star safety hatchback. Gorgeous inside out.",
        "score_performance": 7, "score_comfort": 7, "score_safety": 10,
        "score_value": 8, "score_tech": 7, "score_space": 7,
    },
    {
        "name": "Tata Tigor",
        "image": "tigor.png",
        "emoji": "🔷",
        "category": "Sedan",
        "price_min": 7.7, "price_max": 11.5,
        "engine": "1.2L Revotron Petrol",
        "power": "86 PS", "torque": "113 Nm",
        "transmission": "5MT / AMT", "fuel": "Petrol",
        "mileage": "20.3 kmpl", "seating": 5, "boot": 419,
        "safety": "4-Star (GNCAP)",
        "tags": ["Compact Sedan", "Large Boot", "AMT"],
        "tagline": "Stylish compact sedan with a massive boot for the city.",
        "score_performance": 6, "score_comfort": 7, "score_safety": 7,
        "score_value": 8, "score_tech": 6, "score_space": 7,
    },
    {
        "name": "Tata Tigor EV",
        "image": "tigor_ev.png",
        "emoji": "🌿",
        "category": "Electric",
        "price_min": 12.5, "price_max": 14.0,
        "engine": "Electric Motor",
        "power": "74 PS", "torque": "170 Nm",
        "transmission": "Single Speed AT", "fuel": "Electric",
        "mileage": "306 km range", "seating": 5, "boot": 316,
        "safety": "4-Star (GNCAP)",
        "tags": ["EV", "Sedan", "Government Fleet"],
        "tagline": "Electric sedan—clean commuting with sedan practicality.",
        "score_performance": 6, "score_comfort": 7, "score_safety": 7,
        "score_value": 7, "score_tech": 7, "score_space": 7,
    },
    {
        "name": "Tata Nexon",
        "image": "nexon.png",
        "emoji": "🟢",
        "category": "Compact SUV",
        "price_min": 8.1, "price_max": 16.0,
        "engine": "1.2L Petrol / 1.5L Diesel",
        "power": "120–130 PS", "torque": "170–260 Nm",
        "transmission": "6MT / AMT / 7DCT", "fuel": "Petrol / Diesel",
        "mileage": "17–24 kmpl", "seating": 5, "boot": 350,
        "safety": "5-Star (GNCAP)",
        "tags": ["5-Star Safety", "Best Seller", "DCT"],
        "tagline": "India's #1 Sub-4m SUV. Iconic design, unbeatable safety.",
        "score_performance": 8, "score_comfort": 8, "score_safety": 10,
        "score_value": 9, "score_tech": 8, "score_space": 7,
    },
    {
        "name": "Tata Nexon EV",
        "image": "nexon_ev.png",
        "emoji": "⚡",
        "category": "Electric",
        "price_min": 14.5, "price_max": 20.5,
        "engine": "Electric Motor (30.2 / 40.5 kWh)",
        "power": "129–143 PS", "torque": "245–250 Nm",
        "transmission": "Single Speed AT", "fuel": "Electric",
        "mileage": "312–465 km range", "seating": 5, "boot": 350,
        "safety": "5-Star (GNCAP)",
        "tags": ["EV", "5-Star Safety", "Fast Charge"],
        "tagline": "India's most popular EV—powerful, safe, and future-ready.",
        "score_performance": 8, "score_comfort": 8, "score_safety": 10,
        "score_value": 8, "score_tech": 9, "score_space": 7,
    },
    {
        "name": "Tata Punch",
        "image": "punch.png",
        "emoji": "🟡",
        "category": "Compact SUV",
        "price_min": 6.1, "price_max": 10.5,
        "engine": "1.2L Revotron Petrol",
        "power": "86 PS", "torque": "113 Nm",
        "transmission": "5MT / AMT", "fuel": "Petrol",
        "mileage": "18.8 kmpl", "seating": 5, "boot": 366,
        "safety": "5-Star (GNCAP)",
        "tags": ["Micro SUV", "5-Star Safety", "Adventure"],
        "tagline": "Micro SUV with a massive heart—safety and style in one.",
        "score_performance": 6, "score_comfort": 7, "score_safety": 10,
        "score_value": 9, "score_tech": 7, "score_space": 6,
    },
    {
        "name": "Tata Punch EV",
        "image": "punch_ev.png",
        "emoji": "⚡",
        "category": "Electric",
        "price_min": 10.9, "price_max": 15.5,
        "engine": "Electric Motor (25 / 35 kWh)",
        "power": "82–122 PS", "torque": "114–190 Nm",
        "transmission": "Single Speed AT", "fuel": "Electric",
        "mileage": "301–421 km range", "seating": 5, "boot": 366,
        "safety": "5-Star (GNCAP)",
        "tags": ["EV", "5-Star Safety", "Micro SUV"],
        "tagline": "Electrify your adventure—the Punch goes green.",
        "score_performance": 7, "score_comfort": 7, "score_safety": 10,
        "score_value": 8, "score_tech": 8, "score_space": 6,
    },
    {
        "name": "Tata Harrier",
        "image": "harrier.png",
        "emoji": "🔴",
        "category": "SUV",
        "price_min": 15.5, "price_max": 26.5,
        "engine": "2.0L Kryotec Diesel / 1.5L Petrol Turbo",
        "power": "168–170 PS", "torque": "350 Nm",
        "transmission": "6MT / 6AT", "fuel": "Diesel / Petrol",
        "mileage": "14.6–16.8 kmpl", "seating": 5, "boot": 425,
        "safety": "5-Star (GNCAP)",
        "tags": ["5-Star Safety", "Flagship", "Sunroof", "ADAS"],
        "tagline": "India's iconic bold SUV—confidence on every terrain.",
        "score_performance": 9, "score_comfort": 9, "score_safety": 10,
        "score_value": 8, "score_tech": 9, "score_space": 8,
    },
    {
        "name": "Tata Safari",
        "image": "safari.png",
        "emoji": "🟠",
        "category": "SUV",
        "price_min": 16.5, "price_max": 28.0,
        "engine": "2.0L Kryotec Diesel / 1.5L Petrol Turbo",
        "power": "168–170 PS", "torque": "350 Nm",
        "transmission": "6MT / 6AT", "fuel": "Diesel / Petrol",
        "mileage": "14.5–16.3 kmpl", "seating": 6, "boot": 447,
        "safety": "5-Star (GNCAP)",
        "tags": ["5-Star Safety", "6/7 Seater", "ADAS", "3-Row"],
        "tagline": "The legend reborn—3-row SUV royalty for the whole family.",
        "score_performance": 9, "score_comfort": 9, "score_safety": 10,
        "score_value": 8, "score_tech": 9, "score_space": 9,
    },
    {
        "name": "Tata Curvv",
        "image": "curvv.png",
        "emoji": "🌀",
        "category": "SUV",
        "price_min": 10.0, "price_max": 19.0,
        "engine": "1.2L Turbo Petrol / 1.5L Diesel",
        "power": "123–125 PS", "torque": "170–260 Nm",
        "transmission": "6MT / 7DCT", "fuel": "Petrol / Diesel",
        "mileage": "16–21 kmpl", "seating": 5, "boot": 500,
        "safety": "5-Star (GNCAP)",
        "tags": ["Coupe SUV", "New 2024", "ADAS", "Panoramic"],
        "tagline": "India's first coupe SUV. Drama on four wheels.",
        "score_performance": 8, "score_comfort": 9, "score_safety": 10,
        "score_value": 8, "score_tech": 9, "score_space": 8,
    },
    {
        "name": "Tata Curvv EV",
        "image": "curvv_ev.png",
        "emoji": "⚡",
        "category": "Electric",
        "price_min": 17.5, "price_max": 22.0,
        "engine": "Electric Motor (45 / 55 kWh)",
        "power": "150–167 PS", "torque": "215 Nm",
        "transmission": "Single Speed AT", "fuel": "Electric",
        "mileage": "502–585 km range", "seating": 5, "boot": 500,
        "safety": "5-Star (GNCAP)",
        "tags": ["EV", "Coupe SUV", "Long Range", "ADAS"],
        "tagline": "The future is stylish—long range coupe EV for India.",
        "score_performance": 9, "score_comfort": 9, "score_safety": 10,
        "score_value": 7, "score_tech": 10, "score_space": 8,
    },
    {
        "name": "Tata Sierra EV",
        "image": "sierra_ev.png",
        "emoji": "🏔️",
        "category": "Electric",
        "price_min": 25.0, "price_max": 35.0,
        "engine": "Electric Motor (60+ kWh)",
        "power": "200+ PS", "torque": "300+ Nm",
        "transmission": "Single Speed AT", "fuel": "Electric",
        "mileage": "500+ km range", "seating": 5, "boot": 480,
        "safety": "5-Star (GNCAP)",
        "tags": ["EV", "Iconic", "Premium", "New 2025"],
        "tagline": "The iconic Sierra reborn as a premium electric SUV.",
        "score_performance": 9, "score_comfort": 9, "score_safety": 10,
        "score_value": 7, "score_tech": 10, "score_space": 8,
    },
    {
        "name": "Tata Nexon Facelift",
        "image": "nexon_facelift.png",
        "emoji": "💎",
        "category": "Compact SUV",
        "price_min": 9.0, "price_max": 17.5,
        "engine": "1.2L Turbo Petrol / 1.5L Diesel",
        "power": "120–130 PS", "torque": "170–260 Nm",
        "transmission": "6MT / 7DCT / AMT", "fuel": "Petrol / Diesel",
        "mileage": "17–24 kmpl", "seating": 5, "boot": 382,
        "safety": "5-Star (GNCAP)",
        "tags": ["5-Star Safety", "2024 Refresh", "ADAS", "Panoramic"],
        "tagline": "The best gets better—refreshed Nexon with ADAS & panoramic roof.",
        "score_performance": 8, "score_comfort": 9, "score_safety": 10,
        "score_value": 9, "score_tech": 9, "score_space": 8,
    },
]